---
pool:
  vmImage: ubuntu-22.04
name: gameoflife
trigger:
  - master
stages:
  - stage: stage1
    displayName: gol-stage1
    jobs:
      - job: job1
        displayName: gol-job1
        steps:
          - task: Maven@3
            inputs:
              mavenPOMFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              jdkDirectory: '/usr/lib/jvm/java-8-openjdk-amd64'
